INFO 2018-10-17 16:18:45,925 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 16:18:50,923 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 16:42:34,542 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2018-10-17 16:42:34,549 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 16:42:34,580 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 16:42:34,584 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 16:42:44,566 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 16:42:52,394 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 16:43:00,117 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 16:43:03,104 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 16:43:28,110 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 16:43:50,236 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 16:43:58,309 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 16:44:00,222 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 16:45:41,054 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 16:46:46,683 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 16:46:49,760 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 16:46:51,117 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 16:46:52,298 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:00:04,595 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 17:00:11,166 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:00:12,680 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:00:53,525 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:02:25,176 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:02:55,147 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:04:51,370 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:06:46,955 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:06:48,352 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 17:06:58,216 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:07:01,203 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:07:07,615 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:07:53,808 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:07:56,382 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:07:58,681 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:08:01,427 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:12:42,022 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 17:12:45,760 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:12:48,320 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:12:53,075 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:13:02,844 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:13:44,798 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:17:32,452 basehttp 124 "GET /api/orderv1/?out_time1=2018-10-01&out_time2=2018-10-17&page=1 HTTP/1.1" 200 53536
INFO 2018-10-17 17:17:42,453 basehttp 124 "GET /api/orderv1/?out_time1=2018-10-01&out_time2=2018-10-17&page=2 HTTP/1.1" 200 64886
INFO 2018-10-17 17:17:57,672 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 17:18:00,101 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:18:13,900 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:18:18,552 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:18:24,686 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:18:52,644 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:19:39,343 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:19:43,746 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:19:46,495 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:20:42,051 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:20:44,915 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:21:27,577 basehttp 124 "GET /api/course/?page=5 HTTP/1.1" 200 7127
INFO 2018-10-17 17:21:30,641 basehttp 124 "GET /api/course/?page=7 HTTP/1.1" 200 7152
INFO 2018-10-17 17:21:31,817 basehttp 124 "GET /api/course/?page=9 HTTP/1.1" 200 7120
INFO 2018-10-17 17:21:33,959 basehttp 124 "GET /api/course/?page=11 HTTP/1.1" 200 7129
INFO 2018-10-17 17:21:35,795 basehttp 124 "GET /api/course/?page=13 HTTP/1.1" 200 7131
INFO 2018-10-17 17:21:38,014 basehttp 124 "GET /api/course/?page=2251 HTTP/1.1" 200 3823
INFO 2018-10-17 17:25:21,079 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:29:56,653 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:30:10,587 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:30:18,720 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:30:20,857 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:30:28,458 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 17:30:35,782 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:30:40,233 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:30:40,276 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:30:44,520 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:30:52,890 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:30:55,308 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:31:06,709 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 17:31:15,187 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:31:16,264 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:31:21,909 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:31:23,450 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 17:31:26,575 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:31:27,956 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:29,114 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1024
INFO 2018-10-17 17:31:29,959 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:30,993 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:31,502 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:33,140 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:34,697 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:36,673 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:38,860 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:40,621 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:43,652 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:45,403 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:31:52,215 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:32:37,486 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 17:32:44,984 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:32:48,528 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:35:03,587 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:35:03,986 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:35:04,272 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:35:04,425 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:35:04,512 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:35:04,601 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:36:10,770 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:36:13,130 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:36:19,194 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
ERROR 2018-10-17 17:36:38,803 log 228 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 30, in acc_login
    if user.is_staff == 1:
AttributeError: 'NoneType' object has no attribute 'is_staff'
ERROR 2018-10-17 17:36:38,807 basehttp 124 "POST /api/login/ HTTP/1.1" 500 27
INFO 2018-10-17 17:36:43,606 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:36:44,722 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:38:00,804 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-17 17:38:02,075 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:38:05,915 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:38:17,345 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:38:20,983 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:38:25,805 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:38:28,379 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 17:38:51,409 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:40:07,982 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:40:20,817 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:40:21,838 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:40:23,064 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 17:40:27,792 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:44:59,575 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17935
INFO 2018-10-17 17:45:02,280 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48216
INFO 2018-10-17 17:45:05,102 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 17:45:11,788 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 17:45:16,205 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 17:45:28,622 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 17:45:30,105 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 704
INFO 2018-10-17 17:45:37,676 basehttp 124 "GET /api/userlist/?username=&is_staff=0 HTTP/1.1" 200 77
INFO 2018-10-17 18:02:00,264 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2018-10-17 18:02:00,271 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:00,307 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:00,311 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:05,931 basehttp 124 "GET /rbac/ HTTP/1.1" 200 318
INFO 2018-10-17 18:02:06,485 basehttp 124 "GET /rbac/ HTTP/1.1" 200 318
INFO 2018-10-17 18:02:06,783 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:06,785 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:09,072 basehttp 124 "GET /rbac/roles/ HTTP/1.1" 200 1608
INFO 2018-10-17 18:02:09,121 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:09,124 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:11,483 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:11,490 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:12,588 basehttp 124 "GET /rbac/users/ HTTP/1.1" 200 3299
INFO 2018-10-17 18:02:12,620 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:12,625 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:39,910 basehttp 124 "GET /rbac/users/edit/1/ HTTP/1.1" 200 1131
INFO 2018-10-17 18:02:39,941 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:39,945 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:44,454 basehttp 124 "POST /rbac/users/edit/1/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:44,463 basehttp 124 "GET /%2Fusers/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:44,473 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:44,524 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:44,535 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:45,952 basehttp 124 "GET /rbac/users/edit/1/ HTTP/1.1" 200 1131
INFO 2018-10-17 18:02:45,974 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:45,977 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:48,173 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:48,177 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:02:50,450 basehttp 124 "GET /rbac/users/new/ HTTP/1.1" 200 1076
INFO 2018-10-17 18:02:50,467 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:02:50,472 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:03:15,125 basehttp 124 "POST /rbac/users/new/ HTTP/1.1" 302 0
INFO 2018-10-17 18:03:15,129 basehttp 124 "GET /%2Fusers/ HTTP/1.1" 302 0
INFO 2018-10-17 18:03:15,134 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:03:15,152 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:03:15,157 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:03:16,662 basehttp 124 "GET /rbac/users/new/ HTTP/1.1" 200 1076
INFO 2018-10-17 18:03:16,701 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-17 18:03:16,704 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-17 18:21:02,906 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-17 18:21:11,300 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17768
INFO 2018-10-17 18:21:12,477 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-17 18:21:14,493 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-17 18:21:46,626 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-17 18:21:46,797 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 866
INFO 2018-10-17 18:23:03,777 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-17 18:23:03,898 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 938
INFO 2018-10-17 18:23:11,757 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 18:23:23,155 basehttp 124 "POST /api/login/ HTTP/1.1" 200 15
INFO 2018-10-17 18:23:28,662 basehttp 124 "POST /api/login/ HTTP/1.1" 200 15
INFO 2018-10-17 18:23:34,778 basehttp 124 "POST /api/login/ HTTP/1.1" 200 15
INFO 2018-10-17 18:24:10,914 basehttp 124 "POST /api/login/ HTTP/1.1" 200 15
INFO 2018-10-17 18:24:16,026 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1104
INFO 2018-10-17 18:24:17,129 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17917
INFO 2018-10-17 18:24:19,039 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 938
INFO 2018-10-17 18:25:14,920 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-17 18:25:21,258 basehttp 124 "POST /api/login/ HTTP/1.1" 200 574
ERROR 2018-10-17 18:26:15,457 log 228 Internal Server Error: /api/login/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 35, in acc_login
    if user.is_staff == 1:
AttributeError: 'NoneType' object has no attribute 'is_staff'
ERROR 2018-10-17 18:26:15,458 basehttp 124 "POST /api/login/ HTTP/1.1" 500 27
INFO 2018-10-17 18:26:19,653 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1104
INFO 2018-10-17 18:26:21,450 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 17917
INFO 2018-10-17 18:26:22,772 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-17 18:28:39,417 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-17 18:28:39,579 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 866
INFO 2018-10-17 18:56:06,221 basehttp 124 "POST /api/order/?order_status=[] HTTP/1.1" 200 15
INFO 2018-10-17 18:58:24,132 basehttp 124 "POST /api/order/?order_status=[] HTTP/1.1" 200 15
INFO 2018-10-17 18:58:36,601 basehttp 124 "GET /api/order/?order_status=[] HTTP/1.1" 200 15
INFO 2018-10-18 10:10:54,350 basehttp 124 "POST /api/userlist/ HTTP/1.1" 302 0
INFO 2018-10-18 10:10:58,068 basehttp 124 "POST /api/userlist/ HTTP/1.1" 302 0
INFO 2018-10-18 10:11:18,929 basehttp 124 "POST /api/userlist/ HTTP/1.1" 302 0
ERROR 2018-10-18 10:12:04,891 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\virtualenv\env2\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\virtualenv\env2\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 153, in post
    print(model_form)
  File "D:\virtualenv\env2\lib\site-packages\django\utils\html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "D:\virtualenv\env2\lib\site-packages\django\forms\forms.py", line 142, in __str__
    return self.as_table()
  File "D:\virtualenv\env2\lib\site-packages\django\forms\forms.py", line 284, in as_table
    errors_on_separate_row=False,
  File "D:\virtualenv\env2\lib\site-packages\django\forms\forms.py", line 202, in _html_output
    top_errors = self.non_field_errors()  # Errors that should be displayed above all fields.
  File "D:\virtualenv\env2\lib\site-packages\django\forms\forms.py", line 313, in non_field_errors
    return self.errors.get(NON_FIELD_ERRORS, self.error_class(error_class='nonfield'))
  File "D:\virtualenv\env2\lib\site-packages\django\forms\forms.py", line 180, in errors
    self.full_clean()
  File "D:\virtualenv\env2\lib\site-packages\django\forms\forms.py", line 381, in full_clean
    self._clean_fields()
  File "D:\virtualenv\env2\lib\site-packages\django\forms\forms.py", line 393, in _clean_fields
    value = field.widget.value_from_datadict(self.data, self.files, self.add_prefix(name))
  File "D:\virtualenv\env2\lib\site-packages\django\forms\widgets.py", line 246, in value_from_datadict
    return data.get(name)
AttributeError: 'bytes' object has no attribute 'get'
ERROR 2018-10-18 10:12:04,898 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 10:13:28,621 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 10:23:16,659 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-18 10:23:20,519 basehttp 124 "GET /api/course/?page=-1 HTTP/1.1" 200 102
INFO 2018-10-18 10:23:29,607 basehttp 124 "GET /api/course/?course_datetime1=2018-10-10&course_datetime2=2018-10-18&page=-1 HTTP/1.1" 200 1545353
INFO 2018-10-18 10:25:19,981 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 10:25:38,899 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 10:26:11,787 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 11:26:29,319 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
ERROR 2018-10-18 11:28:02,243 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 158, in userlist
    password = model_form.password
AttributeError: 'UserInfoModelForm' object has no attribute 'password'
ERROR 2018-10-18 11:28:02,246 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 11:30:03,597 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 161, in userlist
    'model_form': model_form
  File "D:\virtualenv\env2\lib\site-packages\django\http\response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserInfoModelForm is not JSON serializable
ERROR 2018-10-18 11:30:03,665 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 11:36:18,571 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 11:37:13,570 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 11:38:50,877 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 942
INFO 2018-10-18 11:39:47,205 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 11:40:30,916 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 13:39:10,363 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
ERROR 2018-10-18 13:49:43,058 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 170, in userlist
    is_staff=True
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\query.py", line 411, in create
    obj = self.model(**kwargs)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\base.py", line 480, in __init__
    _setattr(self, prop, kwargs[prop])
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\fields\related_descriptors.py", line 537, in __set__
    % self._get_set_deprecation_msg_params(),
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use roles.set() instead.
ERROR 2018-10-18 13:49:43,076 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 13:57:36,455 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17984
INFO 2018-10-18 13:57:37,366 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
WARNING 2018-10-18 13:58:35,613 log 228 Not Found: /api/userlist/12/
WARNING 2018-10-18 13:58:35,614 basehttp 124 "POST /api/userlist/12/ HTTP/1.1" 404 90
INFO 2018-10-18 14:00:21,552 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:01:17,990 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:02:01,598 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:02:23,211 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:02:25,646 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:03:25,936 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:03:28,052 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:03:31,452 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:03:47,529 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:05:25,763 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:05:36,273 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:05:45,535 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:07:55,749 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1104
INFO 2018-10-18 14:07:58,591 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:07:58,945 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18056
INFO 2018-10-18 14:08:05,581 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:08:06,962 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:08:16,062 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:09:09,144 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:09:36,064 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:09:36,064 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:09:42,833 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:10:14,407 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:10:14,520 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:10:17,463 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:11:04,249 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:11:05,125 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:11:19,041 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:11:52,308 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:12:05,329 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:12:09,910 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:12:18,926 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:12:40,204 basehttp 124 "GET /api/userlist/?username=&is_staff=1 HTTP/1.1" 200 717
INFO 2018-10-18 14:12:43,037 basehttp 124 "GET /api/userlist/?username=&is_staff=0 HTTP/1.1" 200 77
INFO 2018-10-18 14:12:45,953 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:12:59,544 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:14:28,549 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:16:19,314 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:16:19,494 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:16:23,506 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:17:48,325 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:17:48,327 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:18:23,394 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:18:23,422 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:18:26,842 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:18:27,260 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 793
INFO 2018-10-18 14:18:34,064 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:18:34,417 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 793
INFO 2018-10-18 14:18:51,599 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 793
INFO 2018-10-18 14:19:00,772 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:19:01,254 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 793
INFO 2018-10-18 14:19:47,874 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:19:48,492 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 793
INFO 2018-10-18 14:20:38,259 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 14:23:08,337 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 793
INFO 2018-10-18 14:24:44,844 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 793
INFO 2018-10-18 14:24:50,089 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:24:51,214 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
INFO 2018-10-18 14:25:02,973 basehttp 124 "GET /api/userlist/?username=&is_staff=1 HTTP/1.1" 200 717
INFO 2018-10-18 14:25:07,607 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 794
ERROR 2018-10-18 14:28:13,535 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 132, in userlist
    return JsonResponse(user_list, safe=False)
  File "D:\virtualenv\env2\lib\site-packages\django\http\response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ManyRelatedManager is not JSON serializable
ERROR 2018-10-18 14:28:13,540 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 14:37:46,833 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 132, in userlist
    return JsonResponse({'user_list': user_list, 'code': 200})
  File "D:\virtualenv\env2\lib\site-packages\django\http\response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ManyRelatedManager is not JSON serializable
ERROR 2018-10-18 14:37:46,838 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 14:40:14,953 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 132, in userlist
    return JsonResponse({'user_list': user_list, 'code': 200})
  File "D:\virtualenv\env2\lib\site-packages\django\http\response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ManyRelatedManager is not JSON serializable
ERROR 2018-10-18 14:40:14,954 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 500 27
INFO 2018-10-18 14:42:39,241 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:43:25,373 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:44:05,590 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:44:05,744 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:44:13,317 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:44:13,600 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:44:38,022 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:44:38,229 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:45:23,594 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:45:23,608 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:45:38,514 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:45:38,625 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:45:40,762 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:45:40,857 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:45:46,163 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:45:46,497 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:47:13,088 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:47:16,750 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:47:17,319 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 14:47:17,937 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:47:59,552 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 14:55:23,841 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-18 14:55:35,076 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1021
INFO 2018-10-18 14:55:39,677 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 15:00:48,444 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-18 15:00:55,969 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1021
INFO 2018-10-18 15:00:58,466 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 15:02:29,307 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:02:29,767 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 15:02:34,144 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-18 15:02:41,112 basehttp 124 "POST /api/login/ HTTP/1.1" 200 922
INFO 2018-10-18 15:02:43,170 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 15:02:45,389 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-18 15:02:45,443 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17984
INFO 2018-10-18 15:02:46,849 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 15:02:51,694 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 15:03:57,336 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-18 15:04:09,406 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1104
INFO 2018-10-18 15:04:11,939 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 15:04:12,383 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 15:04:16,886 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:04:17,401 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 15:04:28,855 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:04:29,253 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 15:04:34,585 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:04:34,923 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 823
INFO 2018-10-18 15:04:41,122 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:04:41,549 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 823
INFO 2018-10-18 15:04:48,485 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:04:48,856 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 823
INFO 2018-10-18 15:05:01,269 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:05:01,848 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 823
INFO 2018-10-18 15:05:03,924 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:05:04,113 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:05:04,471 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 823
INFO 2018-10-18 15:05:04,893 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 823
INFO 2018-10-18 15:06:22,448 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:22,680 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 823
INFO 2018-10-18 15:06:45,825 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:45,951 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 15:06:48,015 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:48,131 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:49,001 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:49,114 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:51,366 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:51,773 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:53,527 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:53,813 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:54,432 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:54,644 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:54,773 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:55,046 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:55,140 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:55,399 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:55,746 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:56,019 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:56,065 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:56,290 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:56,422 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:56,711 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:56,794 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:57,120 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:57,306 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:57,581 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:06:57,792 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:06:58,236 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:07:57,678 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:07:57,806 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:01,254 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:01,387 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:04,757 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:04,860 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:06,524 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:06,609 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:07,287 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:07,400 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:07,702 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:07,814 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:07,948 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:08,103 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:08,136 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:08,237 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:08:08,410 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:08:08,524 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:10:17,032 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:10:17,178 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 15:11:44,171 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:11:44,469 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 15:11:45,626 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 15:11:45,850 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 16:01:15,074 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 16:02:29,675 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:02:29,883 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 821
INFO 2018-10-18 16:02:47,192 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:02:47,333 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 16:04:37,324 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 16:04:49,024 basehttp 124 "GET /api/orderv1/?s_garden_confirm=1&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 16:04:53,073 basehttp 124 "GET /api/orderv1/?s_garden_confirm=0&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 16:04:56,370 basehttp 124 "GET /api/orderv1/?s_garden_confirm=2&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 16:05:30,104 basehttp 124 "GET /api/orderv1/?s_garden_confirm=2&page=1 HTTP/1.1" 200 62408
INFO 2018-10-18 16:05:47,187 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 822
INFO 2018-10-18 16:11:03,952 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:12:23,552 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:12:23,703 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 895
INFO 2018-10-18 16:13:00,157 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:14:57,589 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:14:57,885 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 896
INFO 2018-10-18 16:15:10,680 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:15:10,863 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 895
INFO 2018-10-18 16:15:29,932 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:15:30,140 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 892
INFO 2018-10-18 16:15:35,732 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:15:35,842 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 891
INFO 2018-10-18 16:18:38,593 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:18:38,732 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 966
INFO 2018-10-18 16:26:49,628 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 16:26:49,794 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 1037
INFO 2018-10-18 16:38:43,636 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
ERROR 2018-10-18 16:45:00,564 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 183, in userlist
    np = model_form.password
AttributeError: 'UserInfoModelForm' object has no attribute 'password'
ERROR 2018-10-18 16:45:00,565 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 16:45:52,971 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 183, in userlist
    np = model_form.password
AttributeError: 'UserInfoModelForm' object has no attribute 'password'
ERROR 2018-10-18 16:45:52,984 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 16:47:31,523 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 179, in userlist
    npassword = model_form.cleaned_data('password')
TypeError: 'dict' object is not callable
ERROR 2018-10-18 16:47:31,530 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 16:49:54,378 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
ERROR 2018-10-18 16:53:56,375 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 179, in userlist
    npassword = model_form.cleaned_data.update(map('password','sssss'),'aaaaa')
TypeError: update expected at most 1 arguments, got 2
ERROR 2018-10-18 16:53:56,380 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 16:55:41,402 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18056
INFO 2018-10-18 16:55:59,279 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18056
INFO 2018-10-18 16:56:11,444 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 16:56:54,943 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-18 16:57:03,576 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17984
INFO 2018-10-18 16:57:12,557 basehttp 124 "GET /api/erp/?page=2 HTTP/1.1" 200 17562
INFO 2018-10-18 16:57:13,986 basehttp 124 "GET /api/erp/?page=3 HTTP/1.1" 200 18243
INFO 2018-10-18 16:57:14,356 basehttp 124 "GET /api/erp?page=6 HTTP/1.1" 301 0
INFO 2018-10-18 16:57:15,807 basehttp 124 "GET /api/erp/?page=6 HTTP/1.1" 200 17237
INFO 2018-10-18 16:57:16,427 basehttp 124 "GET /api/erp?page=7 HTTP/1.1" 301 0
INFO 2018-10-18 16:57:17,848 basehttp 124 "GET /api/erp/?page=7 HTTP/1.1" 200 17417
INFO 2018-10-18 16:57:18,540 basehttp 124 "GET /api/erp?page=8 HTTP/1.1" 301 0
INFO 2018-10-18 16:57:20,080 basehttp 124 "GET /api/erp/?page=8 HTTP/1.1" 200 17615
ERROR 2018-10-18 17:02:26,539 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 179, in userlist
    password = model_form.cleaned_data.get('password')
AttributeError: 'UserInfoModelForm' object has no attribute 'cleaned_data'
ERROR 2018-10-18 17:02:26,543 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 181, in userlist
    model_form.cleaned_data.update(npassword)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
ERROR 2018-10-18 17:02:26,546 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 17:02:26,549 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 17:06:44,409 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 17:06:44,554 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 960
INFO 2018-10-18 17:26:17,296 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-18 17:26:19,485 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:26:33,329 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:26:39,347 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-18 17:26:41,270 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:26:51,800 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E8%B4%A2%E5%8A%A1%E5%AE%A1%E6%A0%B8&order_status[]=%E5%BE%85%E5%86%85%E6%8E%A7%E5%AE%A1%E6%A0%B8&order_status[]=%E5%BE%85%E7%BD%91%E7%BB%9C%E7%9B%91%E6%B5%8B%E5%AE%89%E8%A3%85&order_status[]=%E5%86%85%E6%8E%A7%E9%A9%B3%E5%9B%9E&order_status[]=%E5%B7%B2%E6%92%A4%E9%94%80&order_status[]=%E5%9B%AD%E5%8A%A1%E5%BB%B6%E5%90%8E%E5%A4%84%E7%90%86(%E8%AF%BE%E7%A8%8B)&order_status[]=%E5%BE%85%E5%9B%AD%E5%8A%A1%E7%A1%AE%E8%AE%A4(%E5%AE%9E%E7%89%A9)&order_status[]=%E5%9B%AD%E5%8A%A1%E5%BB%B6%E5%90%8E%E5%A4%84%E7%90%86(%E5%AE%9E%E7%89%A9)&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:28:24,654 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%B7%B2%E6%92%A4%E9%94%80&order_status[]=%E5%BE%85%E7%BD%91%E7%BB%9C%E7%9B%91%E6%B5%8B%E5%AE%89%E8%A3%85&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:28:37,415 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:28:39,653 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E7%BD%91%E7%BB%9C%E7%9B%91%E6%B5%8B%E5%AE%89%E8%A3%85&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:28:44,394 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&order_status[]=%E5%BE%85%E8%B4%A2%E5%8A%A1%E5%AE%A1%E6%A0%B8&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:28:45,658 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E8%B4%A2%E5%8A%A1%E5%AE%A1%E6%A0%B8&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:29:19,255 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:29:19,531 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:29:23,048 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:29:23,107 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:29:28,322 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 48976
ERROR 2018-10-18 17:29:42,645 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:29:42,647 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 500 27
ERROR 2018-10-18 17:29:46,454 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:29:46,457 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 500 27
ERROR 2018-10-18 17:29:51,368 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:29:51,369 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 500 27
ERROR 2018-10-18 17:29:57,227 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:29:57,228 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 500 27
ERROR 2018-10-18 17:30:29,215 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:30:29,216 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 500 27
ERROR 2018-10-18 17:30:38,491 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:30:38,491 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 500 27
ERROR 2018-10-18 17:30:51,793 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:30:51,795 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 500 27
ERROR 2018-10-18 17:30:57,907 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 35, in order
    print('order_status' + order_status)
TypeError: can only concatenate str (not "NoneType") to str
ERROR 2018-10-18 17:30:57,910 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 500 27
INFO 2018-10-18 17:32:36,960 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:32:42,877 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17984
INFO 2018-10-18 17:32:44,078 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:32:48,058 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:32:54,262 basehttp 124 "GET /api/orderv1/?school_name=%E6%96%B0%E8%8B%97%E8%89%BA%E6%9C%AF%E5%B9%BC%E7%A8%9A%E5%9B%AD&page=1 HTTP/1.1" 200 3345
INFO 2018-10-18 17:33:03,557 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:33:28,992 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&school_name=%E6%96%B0%E8%8B%97%E8%89%BA%E6%9C%AF%E5%B9%BC%E7%A8%9A%E5%9B%AD&page=1 HTTP/1.1" 200 3345
INFO 2018-10-18 17:34:40,541 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E8%B4%A2%E5%8A%A1%E5%AE%A1%E6%A0%B8&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&order_status[]=%E5%BE%85%E5%86%85%E6%8E%A7%E5%AE%A1%E6%A0%B8&order_status[]=%E5%BE%85%E7%BD%91%E7%BB%9C%E7%9B%91%E6%B5%8B%E5%AE%89%E8%A3%85&order_status[]=%E5%9B%AD%E5%8A%A1%E5%BB%B6%E5%90%8E%E5%A4%84%E7%90%86(%E8%AF%BE%E7%A8%8B)&order_status[]=%E5%86%85%E6%8E%A7%E9%A9%B3%E5%9B%9E&order_status[]=%E5%BE%85%E5%9B%AD%E5%8A%A1%E7%A1%AE%E8%AE%A4(%E5%AE%9E%E7%89%A9)&order_status[]=%E5%9B%AD%E5%8A%A1%E5%BB%B6%E5%90%8E%E5%A4%84%E7%90%86(%E5%AE%9E%E7%89%A9)&school_name=%E6%96%B0%E8%8B%97%E8%89%BA%E6%9C%AF%E5%B9%BC%E7%A8%9A%E5%9B%AD&page=1 HTTP/1.1" 200 3345
INFO 2018-10-18 17:37:13,291 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:38:56,793 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 60767
INFO 2018-10-18 17:39:11,312 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 200 51205
INFO 2018-10-18 17:39:32,513 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&page=4 HTTP/1.1" 200 47449
INFO 2018-10-18 17:39:58,827 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 55141
INFO 2018-10-18 17:40:10,688 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:40:13,477 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 200 51279
INFO 2018-10-18 17:40:18,433 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:40:22,322 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 60767
INFO 2018-10-18 17:41:50,549 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:41:56,604 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&page=1 HTTP/1.1" 200 46995
INFO 2018-10-18 17:42:06,062 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 200 51279
INFO 2018-10-18 17:42:16,144 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 60767
INFO 2018-10-18 17:42:27,623 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 55141
INFO 2018-10-18 17:42:47,356 basehttp 124 "GET /api/orderv1/?s_garden_confirm=0&page=1 HTTP/1.1" 200 63729
INFO 2018-10-18 17:42:52,546 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 17:44:45,394 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 891
INFO 2018-10-18 17:55:52,495 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 17:55:52,815 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 17:56:03,336 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 17:56:03,544 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 960
INFO 2018-10-18 17:56:05,242 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 17:56:05,507 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 17:57:26,674 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 891
INFO 2018-10-18 17:57:47,247 basehttp 124 "GET / HTTP/1.1" 302 0
INFO 2018-10-18 17:57:47,262 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:57:47,308 basehttp 124 "GET /favicon.ico HTTP/1.1" 301 0
INFO 2018-10-18 17:57:47,314 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:57:47,317 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:57:55,988 basehttp 124 "GET /rbac/ HTTP/1.1" 200 318
INFO 2018-10-18 17:57:56,026 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:57:56,029 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:57:57,968 basehttp 124 "GET /rbac/roles/ HTTP/1.1" 200 1608
INFO 2018-10-18 17:57:57,998 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:57:58,002 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:00,745 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:00,748 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:02,222 basehttp 124 "GET /rbac/permissions/ HTTP/1.1" 200 1749
INFO 2018-10-18 17:58:02,234 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:02,237 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:03,572 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:03,576 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:04,668 basehttp 124 "GET /rbac/users/ HTTP/1.1" 200 3920
INFO 2018-10-18 17:58:04,711 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:04,716 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:09,538 basehttp 124 "GET /rbac/users/edit/1 HTTP/1.1" 301 0
INFO 2018-10-18 17:58:10,031 basehttp 124 "GET /rbac/users/edit/1/ HTTP/1.1" 200 1008
INFO 2018-10-18 17:58:10,053 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:10,056 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:16,325 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:16,328 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:19,728 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:19,732 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:22,213 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:22,218 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:23,963 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:23,969 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:26,493 basehttp 124 "GET /rbac/roles/ HTTP/1.1" 200 1608
INFO 2018-10-18 17:58:26,526 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:26,532 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:29,295 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:29,298 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:44,290 basehttp 124 "GET /rbac/permissions/ HTTP/1.1" 200 1749
INFO 2018-10-18 17:58:44,308 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:44,313 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:47,910 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:47,914 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:49,172 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:49,175 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
INFO 2018-10-18 17:58:51,037 basehttp 124 "GET /favicon.ico/ HTTP/1.1" 302 0
INFO 2018-10-18 17:58:51,042 basehttp 124 "GET /api/login/ HTTP/1.1" 200 25
ERROR 2018-10-18 18:13:46,147 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 179, in userlist
    password = model_form.cleaned_data.get('password')
AttributeError: 'UserInfoModelForm' object has no attribute 'cleaned_data'
ERROR 2018-10-18 18:13:46,148 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 18:14:39,246 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:14:43,467 basehttp 124 "GET /api/orderv1/?order_code=&operater=&combo_name=&is_plan=&school_name=&order_create_time1=&order_create_time2=&sales_unit_name=&is_nerwork=&s_garden_confirm=&unpaid_amount=&school_address=&out_time1=&out_time2=&pay_voucher=&agent_linkman=&page=1 HTTP/1.1" 200 48976
ERROR 2018-10-18 18:14:44,621 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 179, in userlist
    password = model_form.cleaned_data.get('password')
AttributeError: 'UserInfoModelForm' object has no attribute 'cleaned_data'
ERROR 2018-10-18 18:14:44,624 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 18:14:59,617 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:14:59,742 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 18:15:13,430 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
ERROR 2018-10-18 18:15:22,687 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 122, in order
    start_date = datetime.datetime.strptime(out_time1, "%Y-%m-%d")
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
ERROR 2018-10-18 18:15:22,703 basehttp 124 "GET /api/orderv1/?order_code=&operater=&combo_name=&order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E8%B4%A2%E5%8A%A1%E5%AE%A1%E6%A0%B8&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&is_plan=&school_name=&order_create_time1=&order_create_time2=&sales_unit_name=&is_nerwork=&s_garden_confirm=&unpaid_amount=&school_address=&out_time1=&out_time2=&pay_voucher=&agent_linkman=&page=1 HTTP/1.1" 500 27
INFO 2018-10-18 18:15:40,348 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:15:46,220 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
ERROR 2018-10-18 18:15:53,102 log 228 Internal Server Error: /api/orderv1/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\combov1\views.py", line 122, in order
    start_date = datetime.datetime.strptime(out_time1, "%Y-%m-%d")
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%d'
ERROR 2018-10-18 18:15:53,104 basehttp 124 "GET /api/orderv1/?order_code=&operater=&combo_name=&order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&order_status[]=%E5%BE%85%E8%B4%A2%E5%8A%A1%E5%AE%A1%E6%A0%B8&is_plan=&school_name=&order_create_time1=&order_create_time2=&sales_unit_name=&is_nerwork=&s_garden_confirm=&unpaid_amount=&school_address=&out_time1=&out_time2=&pay_voucher=&agent_linkman=&page=1 HTTP/1.1" 500 27
INFO 2018-10-18 18:16:13,042 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:16:19,531 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:16:25,096 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&page=1 HTTP/1.1" 200 49884
INFO 2018-10-18 18:17:14,182 basehttp 124 "GET /api/orderv1/?order_status[]=%E9%83%A8%E5%88%86%E5%8F%91%E8%B4%A7&page=1 HTTP/1.1" 200 63609
INFO 2018-10-18 18:17:32,188 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:17:37,880 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 18:17:47,480 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17984
INFO 2018-10-18 18:17:49,934 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 18:19:13,353 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:19:13,561 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 958
INFO 2018-10-18 18:19:14,525 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:19:14,857 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 18:19:53,345 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-18 18:20:01,520 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1101
INFO 2018-10-18 18:20:02,520 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 18:20:07,591 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 18:20:09,033 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 18:20:53,340 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:21:01,957 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:21:02,076 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 18:21:22,811 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-18 18:21:28,331 basehttp 124 "POST /api/login/ HTTP/1.1" 200 922
INFO 2018-10-18 18:21:28,997 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 18:21:31,731 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17984
INFO 2018-10-18 18:21:32,634 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-18 18:21:36,528 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:21:42,577 basehttp 124 "GET /api/orderv1/?s_garden_confirm=1&page=1 HTTP/1.1" 200 51818
INFO 2018-10-18 18:21:45,948 basehttp 124 "GET /api/orderv1/?s_garden_confirm=0&page=1 HTTP/1.1" 200 63729
INFO 2018-10-18 18:21:48,719 basehttp 124 "GET /api/orderv1/?s_garden_confirm=2&page=1 HTTP/1.1" 200 62408
INFO 2018-10-18 18:21:51,374 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:21:55,318 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&page=1 HTTP/1.1" 200 46995
INFO 2018-10-18 18:22:01,396 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E5%8F%91%E8%B4%A7&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&s_garden_confirm=1&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:22:05,008 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:22:10,278 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&s_garden_confirm=0&page=1 HTTP/1.1" 200 59530
INFO 2018-10-18 18:22:13,783 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:22:21,409 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&s_garden_confirm=0&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:23:02,611 basehttp 124 "GET /api/orderv1/?order_status[]=%E8%B4%A2%E5%8A%A1%E9%A9%B3%E5%9B%9E&s_garden_confirm=0&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:23:08,843 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&s_garden_confirm=0&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:23:16,306 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:23:20,691 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&s_garden_confirm=0&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:23:26,616 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&s_garden_confirm=0&page=1 HTTP/1.1" 200 59530
INFO 2018-10-18 18:23:31,761 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%85%A8%E9%83%A8%E5%8F%91%E8%B4%A7&order_status[]=%E5%B8%82%E5%9C%BA%E9%A9%B3%E5%9B%9E&s_garden_confirm=0&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:24:31,476 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:24:49,287 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 18:24:57,173 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 18:25:07,868 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:25:34,905 basehttp 124 "GET /api/orderv1/?page=4 HTTP/1.1" 200 49006
INFO 2018-10-18 18:26:08,559 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&page=1 HTTP/1.1" 200 46995
INFO 2018-10-18 18:26:13,388 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&s_garden_confirm=0&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:26:16,753 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&s_garden_confirm=1&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:26:20,046 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&s_garden_confirm=2&page=1 HTTP/1.1" 200 111
INFO 2018-10-18 18:26:21,349 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:26:26,958 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&page=1 HTTP/1.1" 200 46995
INFO 2018-10-18 18:26:53,472 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&page=2 HTTP/1.1" 200 13486
INFO 2018-10-18 18:26:56,112 basehttp 124 "GET /api/orderv1/?order_status[]=%E5%BE%85%E6%94%AF%E4%BB%98&page=1 HTTP/1.1" 200 46995
INFO 2018-10-18 18:27:09,394 basehttp 124 "GET /api/orderv1/?page=1 HTTP/1.1" 200 48976
INFO 2018-10-18 18:27:22,735 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-18 18:27:35,321 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1104
INFO 2018-10-18 18:27:36,357 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18074
INFO 2018-10-18 18:27:38,522 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 959
INFO 2018-10-18 18:27:57,425 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:27:57,576 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 1027
ERROR 2018-10-18 18:36:27,723 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 182, in userlist
    q.update({'password': npassword})
  File "D:\virtualenv\env2\lib\site-packages\django\utils\datastructures.py", line 205, in update
    self.setlistdefault(key).append(value)
  File "D:\virtualenv\env2\lib\site-packages\django\http\request.py", line 468, in setlistdefault
    self._assert_mutable()
  File "D:\virtualenv\env2\lib\site-packages\django\http\request.py", line 436, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2018-10-18 18:36:27,738 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 18:38:29,793 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 181, in userlist
    request.POST.update({'password': npassword})
  File "D:\virtualenv\env2\lib\site-packages\django\utils\datastructures.py", line 205, in update
    self.setlistdefault(key).append(value)
  File "D:\virtualenv\env2\lib\site-packages\django\http\request.py", line 468, in setlistdefault
    self._assert_mutable()
  File "D:\virtualenv\env2\lib\site-packages\django\http\request.py", line 436, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
ERROR 2018-10-18 18:38:29,794 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 18:40:58,109 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 184, in userlist
    print(model_form.password)
AttributeError: 'UserInfoModelForm' object has no attribute 'password'
ERROR 2018-10-18 18:40:58,110 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 18:41:22,868 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 184, in userlist
    print(npassword)
AttributeError: 'UserInfoModelForm' object has no attribute 'password'
ERROR 2018-10-18 18:41:22,869 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-18 18:41:27,474 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:41:39,386 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-18 18:42:09,255 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
ERROR 2018-10-18 18:51:06,134 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 172, in userlist
    model_form.save()
  File "D:\virtualenv\env2\lib\site-packages\django\forms\models.py", line 453, in save
    'created' if self.instance._state.adding else 'changed',
ValueError: The UserInfo could not be created because the data didn't validate.
ERROR 2018-10-18 18:51:06,138 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 18:55:39,983 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 172, in userlist
    model_form.save()
  File "D:\virtualenv\env2\lib\site-packages\django\forms\models.py", line 453, in save
    'created' if self.instance._state.adding else 'changed',
ValueError: The UserInfo could not be created because the data didn't validate.
ERROR 2018-10-18 18:55:39,985 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 18:56:36,966 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 165, in userlist
    model_form.save()
  File "D:\virtualenv\env2\lib\site-packages\django\forms\models.py", line 453, in save
    'created' if self.instance._state.adding else 'changed',
ValueError: The UserInfo could not be created because the data didn't validate.
ERROR 2018-10-18 18:56:36,967 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 19:08:27,297 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 133, in userlist
    return JsonResponse({'user_list': user_list, 'code': 200})
  File "D:\virtualenv\env2\lib\site-packages\django\http\response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type QuerySet is not JSON serializable
ERROR 2018-10-18 19:08:27,302 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 500 27
INFO 2018-10-18 19:11:46,316 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 891
INFO 2018-10-18 19:12:45,872 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 891
INFO 2018-10-18 19:12:52,249 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 891
ERROR 2018-10-18 19:16:06,677 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 125, in userlist
    user = UserInfo(username=user)
UnboundLocalError: local variable 'user' referenced before assignment
ERROR 2018-10-18 19:16:06,683 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 500 27
ERROR 2018-10-18 19:16:42,040 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 125, in userlist
    user = UserInfo(username=user)
UnboundLocalError: local variable 'user' referenced before assignment
ERROR 2018-10-18 19:16:42,045 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 500 27
ERROR 2018-10-18 19:16:50,764 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 125, in userlist
    user = UserInfo(username=user)
UnboundLocalError: local variable 'user' referenced before assignment
ERROR 2018-10-18 19:16:50,765 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 500 27
ERROR 2018-10-18 19:17:11,387 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 125, in userlist
    user = UserInfo(username=user)
UnboundLocalError: local variable 'user' referenced before assignment
ERROR 2018-10-18 19:17:11,387 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 500 27
ERROR 2018-10-18 19:17:37,354 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 125, in userlist
    user = UserInfo(username=user)
UnboundLocalError: local variable 'user' referenced before assignment
ERROR 2018-10-18 19:17:37,357 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 19:18:38,743 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 128, in userlist
    print(user1)
TypeError: __str__ returned non-string (type UserInfo)
ERROR 2018-10-18 19:18:38,745 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-18 19:22:49,324 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 136, in userlist
    return JsonResponse({'user_list': user_list, 'code': 200})
  File "D:\virtualenv\env2\lib\site-packages\django\http\response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UserInfo is not JSON serializable
ERROR 2018-10-18 19:22:49,326 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-19 09:36:50,209 basehttp 124 "GET /api/orderv1/ HTTP/1.1" 302 0
INFO 2018-10-19 09:37:26,658 basehttp 124 "GET /api/orderv1/ HTTP/1.1" 200 48976
INFO 2018-10-19 10:12:24,235 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 891
INFO 2018-10-19 10:16:23,065 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 741
ERROR 2018-10-19 10:19:17,760 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 129, in userlist
    print(user.roles.all().get('role'))
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\query.py", line 390, in get
    clone = self.filter(*args, **kwargs)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\sql\query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\sql\query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\sql\query.py", line 1161, in build_filter
    arg, value = filter_expr
ValueError: too many values to unpack (expected 2)
ERROR 2018-10-19 10:19:17,799 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-19 10:25:00,845 basehttp 124 "POST /api/login/ HTTP/1.1" 200 922
ERROR 2018-10-19 10:25:00,860 basehttp 124 "POST /api/login/ HTTP/1.1" 500 59
INFO 2018-10-19 10:25:33,909 basehttp 124 "POST /api/login/ HTTP/1.1" 200 922
INFO 2018-10-19 10:25:47,995 basehttp 124 "POST /api/login/ HTTP/1.1" 200 922
INFO 2018-10-19 10:26:45,960 basehttp 124 "GET /api/course/?page=1 HTTP/1.1" 200 7119
INFO 2018-10-19 10:26:48,722 basehttp 124 "GET /api/erp/?page=1 HTTP/1.1" 200 17507
INFO 2018-10-19 10:26:58,764 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18202
INFO 2018-10-19 10:28:04,730 basehttp 124 "GET /api/logout/ HTTP/1.1" 200 13
INFO 2018-10-19 10:28:11,127 basehttp 124 "POST /api/login/ HTTP/1.1" 200 1104
INFO 2018-10-19 10:28:15,199 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 741
INFO 2018-10-19 10:28:16,329 basehttp 124 "GET /api/view/?start=&end= HTTP/1.1" 200 18202
ERROR 2018-10-19 10:39:31,007 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 129, in userlist
    print(list(user.roles.all())['Role'])
TypeError: list indices must be integers or slices, not str
ERROR 2018-10-19 10:39:31,010 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-19 10:40:54,809 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 741
INFO 2018-10-19 10:41:21,402 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 741
ERROR 2018-10-19 10:42:15,605 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 138, in userlist
    return JsonResponse({'user_list': user_list, 'code': 200})
  File "D:\virtualenv\env2\lib\site-packages\django\http\response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\json.py", line 104, in default
    return super().default(o)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Role is not JSON serializable
ERROR 2018-10-19 10:42:15,636 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-19 10:43:45,779 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 741
ERROR 2018-10-19 10:48:21,598 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 133, in userlist
    'roles': user.roles.title,
AttributeError: 'ManyRelatedManager' object has no attribute 'title'
ERROR 2018-10-19 10:48:21,602 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-19 10:49:36,890 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 133, in userlist
    'roles': user.roles.all().title,
AttributeError: 'QuerySet' object has no attribute 'title'
ERROR 2018-10-19 10:49:36,895 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-19 10:51:28,781 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 131, in userlist
    roles = json.dumps(role)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\mp\appdata\local\programs\python\python37\Lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Role is not JSON serializable
ERROR 2018-10-19 10:51:28,785 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-19 10:55:03,213 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 133, in userlist
    roles = serializers.serialize('json', role)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "D:\virtualenv\env2\lib\site-packages\django\core\serializers\base.py", line 87, in serialize
    for count, obj in enumerate(queryset, start=1):
TypeError: 'Role' object is not iterable
ERROR 2018-10-19 10:55:03,226 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-19 10:56:01,177 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 741
INFO 2018-10-19 10:57:01,498 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 2015
ERROR 2018-10-19 10:57:57,546 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 134, in userlist
    print(roles['fields']['title'])
TypeError: string indices must be integers
ERROR 2018-10-19 10:57:57,549 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-19 11:06:50,522 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 134, in userlist
    roles_str = roles.loads(roles)
AttributeError: 'str' object has no attribute 'loads'
ERROR 2018-10-19 11:06:50,524 basehttp 124 "GET /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-19 11:08:35,226 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 2015
INFO 2018-10-19 11:10:09,530 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 2015
INFO 2018-10-19 11:11:07,130 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 2015
INFO 2018-10-19 11:11:33,669 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 2015
INFO 2018-10-19 11:12:12,152 basehttp 124 "GET /api/userlist/ HTTP/1.1" 200 1068
ERROR 2018-10-19 11:25:13,553 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 179, in userlist
    c = UserInfo(username=username,password=password,first_name=first_name,roles=roles,is_staff=True)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\base.py", line 480, in __init__
    _setattr(self, prop, kwargs[prop])
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\fields\related_descriptors.py", line 537, in __set__
    % self._get_set_deprecation_msg_params(),
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use roles.set() instead.
ERROR 2018-10-19 11:25:13,584 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
ERROR 2018-10-19 11:26:28,726 log 228 Internal Server Error: /api/userlist/
Traceback (most recent call last):
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\virtualenv\env2\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\123\lb-dataworks\login\views.py", line 180, in userlist
    c.roles.set(roles)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\fields\related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "D:\virtualenv\env2\lib\site-packages\django\db\models\fields\related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<UserInfo: wq>" needs to have a value for field "id" before this many-to-many relationship can be used.
ERROR 2018-10-19 11:26:28,727 basehttp 124 "POST /api/userlist/ HTTP/1.1" 500 27
INFO 2018-10-19 11:28:04,216 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-19 11:29:52,009 basehttp 124 "POST /api/userlist/ HTTP/1.1" 200 13
INFO 2018-10-19 11:29:56,605 basehttp 124 "GET /api/userlist/?username=&is_staff= HTTP/1.1" 200 1173
